# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(396, 527)
        self.model_cmb = ComboBox(Form)
        self.model_cmb.setGeometry(QtCore.QRect(20, 50, 351, 32))
        self.model_cmb.setObjectName("model_cmb")
        self.microphone_cmb = ComboBox(Form)
        self.microphone_cmb.setGeometry(QtCore.QRect(20, 110, 351, 32))
        self.microphone_cmb.setObjectName("microphone_cmb")
        self.model_lbl = CaptionLabel(Form)
        self.model_lbl.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.model_lbl.setObjectName("model_lbl")
        self.microphone_lbl = CaptionLabel(Form)
        self.microphone_lbl.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.microphone_lbl.setObjectName("microphone_lbl")
        self.OpenAi_key_txt = LineEdit(Form)
        self.OpenAi_key_txt.setGeometry(QtCore.QRect(20, 180, 351, 33))
        self.OpenAi_key_txt.setObjectName("OpenAi_key_txt")
        self.toggle_voice_txt = LineEdit(Form)
        self.toggle_voice_txt.setGeometry(QtCore.QRect(20, 250, 311, 33))
        self.toggle_voice_txt.setObjectName("toggle_voice_txt")
        self.command_txt = TextEdit(Form)
        self.command_txt.setGeometry(QtCore.QRect(20, 320, 351, 151))
        self.command_txt.setObjectName("command_txt")
        self.send_command_btn = PushButton(Form)
        self.send_command_btn.setGeometry(QtCore.QRect(20, 480, 351, 32))
        self.send_command_btn.setObjectName("send_command_btn")
        self.OpenAI_api_lbl = CaptionLabel(Form)
        self.OpenAI_api_lbl.setGeometry(QtCore.QRect(20, 160, 131, 16))
        self.OpenAI_api_lbl.setObjectName("OpenAI_api_lbl")
        self.hotkey_lbl = CaptionLabel(Form)
        self.hotkey_lbl.setGeometry(QtCore.QRect(20, 230, 141, 16))
        self.hotkey_lbl.setObjectName("hotkey_lbl")
        self.CaptionLabel_5 = CaptionLabel(Form)
        self.CaptionLabel_5.setGeometry(QtCore.QRect(20, 300, 121, 16))
        self.CaptionLabel_5.setObjectName("CaptionLabel_5")
        self.voice_status_radio = RadioButton(Form)
        self.voice_status_radio.setEnabled(False)
        self.voice_status_radio.setGeometry(QtCore.QRect(340, 255, 31, 24))
        self.voice_status_radio.setText("")
        self.voice_status_radio.setObjectName("voice_status_radio")
        self.send_loading_ring = IndeterminateProgressRing(Form)
        self.send_loading_ring.setEnabled(True)
        self.send_loading_ring.setGeometry(QtCore.QRect(150, 350, 80, 80))
        self.send_loading_ring.setObjectName("send_loading_ring")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.model_lbl.setText(_translate("Form", "Model :"))
        self.microphone_lbl.setText(_translate("Form", "Microphone :"))
        self.send_command_btn.setText(_translate("Form", "Send"))
        self.OpenAI_api_lbl.setText(_translate("Form", "OpenAI API Key :"))
        self.hotkey_lbl.setText(_translate("Form", "Toggle Voice Hotkey :"))
        self.CaptionLabel_5.setText(_translate("Form", "Text Command Input:"))
from qfluentwidgets import CaptionLabel, ComboBox, IndeterminateProgressRing, LineEdit, PushButton, RadioButton, TextEdit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
