# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(396, 527)
        self.ComboBox = ComboBox(Form)
        self.ComboBox.setGeometry(QtCore.QRect(20, 50, 351, 32))
        self.ComboBox.setObjectName("ComboBox")
        self.ComboBox_2 = ComboBox(Form)
        self.ComboBox_2.setGeometry(QtCore.QRect(20, 110, 351, 32))
        self.ComboBox_2.setObjectName("ComboBox_2")
        self.CaptionLabel = CaptionLabel(Form)
        self.CaptionLabel.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.CaptionLabel_2 = CaptionLabel(Form)
        self.CaptionLabel_2.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.LineEdit = LineEdit(Form)
        self.LineEdit.setGeometry(QtCore.QRect(20, 180, 351, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.LineEdit_2 = LineEdit(Form)
        self.LineEdit_2.setGeometry(QtCore.QRect(20, 250, 311, 33))
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.TextEdit = TextEdit(Form)
        self.TextEdit.setGeometry(QtCore.QRect(20, 320, 351, 151))
        self.TextEdit.setObjectName("TextEdit")
        self.PushButton = PushButton(Form)
        self.PushButton.setGeometry(QtCore.QRect(20, 480, 351, 32))
        self.PushButton.setObjectName("PushButton")
        self.CaptionLabel_3 = CaptionLabel(Form)
        self.CaptionLabel_3.setGeometry(QtCore.QRect(20, 160, 131, 16))
        self.CaptionLabel_3.setObjectName("CaptionLabel_3")
        self.CaptionLabel_4 = CaptionLabel(Form)
        self.CaptionLabel_4.setGeometry(QtCore.QRect(20, 230, 141, 16))
        self.CaptionLabel_4.setObjectName("CaptionLabel_4")
        self.CaptionLabel_5 = CaptionLabel(Form)
        self.CaptionLabel_5.setGeometry(QtCore.QRect(20, 300, 121, 16))
        self.CaptionLabel_5.setObjectName("CaptionLabel_5")
        self.RadioButton = RadioButton(Form)
        self.RadioButton.setGeometry(QtCore.QRect(340, 250, 31, 24))
        self.RadioButton.setText("")
        self.RadioButton.setObjectName("RadioButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CaptionLabel.setText(_translate("Form", "Model :"))
        self.CaptionLabel_2.setText(_translate("Form", "Microphone :"))
        self.PushButton.setText(_translate("Form", "Push button"))
        self.CaptionLabel_3.setText(_translate("Form", "OpenAI API Key :"))
        self.CaptionLabel_4.setText(_translate("Form", "Toggle Voice Hotkey :"))
        self.CaptionLabel_5.setText(_translate("Form", "Text Command Input:"))
from qfluentwidgets import CaptionLabel, ComboBox, LineEdit, PushButton, RadioButton, TextEdit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
