# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(396, 296)
        self.model_cmb = ComboBox(Form)
        self.model_cmb.setGeometry(QtCore.QRect(20, 40, 351, 32))
        self.model_cmb.setObjectName("model_cmb")
        self.microphone_cmb = ComboBox(Form)
        self.microphone_cmb.setGeometry(QtCore.QRect(20, 180, 351, 32))
        self.microphone_cmb.setObjectName("microphone_cmb")
        self.model_lbl = CaptionLabel(Form)
        self.model_lbl.setGeometry(QtCore.QRect(20, 20, 141, 16))
        self.model_lbl.setObjectName("model_lbl")
        self.OpenAi_key_txt = LineEdit(Form)
        self.OpenAi_key_txt.setGeometry(QtCore.QRect(20, 250, 351, 33))
        self.OpenAi_key_txt.setObjectName("OpenAi_key_txt")
        self.voice_lbl = CaptionLabel(Form)
        self.voice_lbl.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.voice_lbl.setObjectName("voice_lbl")
        self.microphone_lbl = CaptionLabel(Form)
        self.microphone_lbl.setGeometry(QtCore.QRect(20, 160, 81, 16))
        self.microphone_lbl.setObjectName("microphone_lbl")
        self.OpenAI_api_lbl = CaptionLabel(Form)
        self.OpenAI_api_lbl.setGeometry(QtCore.QRect(20, 230, 131, 16))
        self.OpenAI_api_lbl.setObjectName("OpenAI_api_lbl")
        self.voice_cmb = ComboBox(Form)
        self.voice_cmb.setGeometry(QtCore.QRect(20, 110, 351, 32))
        self.voice_cmb.setObjectName("voice_cmb")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.model_lbl.setText(_translate("Form", "Large Language Model :"))
        self.voice_lbl.setText(_translate("Form", "Voice Model :"))
        self.microphone_lbl.setText(_translate("Form", "Microphone :"))
        self.OpenAI_api_lbl.setText(_translate("Form", "OpenAI API Key :"))
from qfluentwidgets import CaptionLabel, ComboBox, LineEdit
